"use client";

import { AlertCircle, AlertTriangle, Lightbulb, TrendingUp, ArrowRight, Activity, Calendar, Database, Download } from "lucide-react";
import Header from "@/components/layout/Header";
import InsightCard from "@/components/ui/InsightCard";
import HealthScoreCard from "@/components/ui/HealthScoreCard";
import { useData } from "@/context/DataContext";
import {
  getOverviewInsights,
  getSalesInsights,
  getProductInsights,
  getCustomerInsights,
  getForecastInsights,
  getHealthScore,
  type Insight,
  type InsightType,
} from "@/lib/insightEngine";
import { cn } from "@/lib/utils";

const TYPE_ORDER: InsightType[] = ["critical", "warning", "opportunity", "positive"];

const SECTION_LABELS: Record<string, string> = {
  critical:    "Action Required",
  warning:     "Watch Items",
  opportunity: "Growth Opportunities",
  positive:    "Strengths",
};

const SECTION_DESCRIPTIONS: Record<string, string> = {
  critical:    "These issues are actively eroding margin or revenue and require immediate attention.",
  warning:     "Metrics that are trending toward a problem — monitor and intervene before they worsen.",
  opportunity: "Data-backed opportunities where acting now would generate disproportionate return.",
  positive:    "Areas where the business is outperforming benchmarks — signals to protect and replicate.",
};

const SECTION_ICON: Record<InsightType, React.ElementType> = {
  critical:    AlertCircle,
  warning:     AlertTriangle,
  opportunity: Lightbulb,
  positive:    TrendingUp,
};

const SECTION_COLOR: Record<InsightType, string> = {
  critical:    "text-red-600",
  warning:     "text-amber-600",
  opportunity: "text-blue-600",
  positive:    "text-emerald-600",
};

const SOURCE_LABELS: Record<string, string> = {
  overview:    "Overview",
  sales:       "Sales",
  products:    "Products",
  customers:   "Customers",
  forecasting: "Forecasting",
};

interface TaggedInsight extends Insight {
  source: string;
}

export default function InsightsPage() {
  const { data } = useData();

  const now = new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });

  const tagged: TaggedInsight[] = [
    ...getOverviewInsights(data).map((i) => ({ ...i, source: "overview" })),
    ...getSalesInsights(data).map((i)    => ({ ...i, source: "sales" })),
    ...getProductInsights(data).map((i)  => ({ ...i, source: "products" })),
    ...getCustomerInsights(data).map((i) => ({ ...i, source: "customers" })),
    ...getForecastInsights(data).map((i) => ({ ...i, source: "forecasting" })),
  ];

  const grouped = TYPE_ORDER.reduce<Record<InsightType, TaggedInsight[]>>((acc, type) => {
    acc[type] = tagged.filter((i) => i.type === type);
    return acc;
  }, { critical: [], warning: [], opportunity: [], positive: [] });

  const healthScore = getHealthScore(data);

  const totalRevenue = data.monthlyRevenue.reduce((s, m) => s + m.revenue, 0);
  const totalCustomers = data.customerSegments.reduce((s, c) => s + c.count, 0);
  const totalOrders = data.monthlyRevenue.reduce((s, m) => s + m.orders, 0);

  return (
    <>
      <Header
        title="Insights Report"
        subtitle={`Full business intelligence briefing — ${data.period}${data.isCustomData ? ` · ${data.companyName}` : " · Demo Data"}`}
        action={
          <button
            data-print-hide
            onClick={() => window.print()}
            className="flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700 transition-colors"
          >
            <Download className="h-4 w-4" />
            Download PDF
          </button>
        }
      />

      <div className="flex-1 p-8 space-y-10">

        {/* Report header */}
        <div className="rounded-2xl border border-slate-200 bg-white p-6">
          <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-6">
            <div className="flex-1">
              <p className="text-[11px] font-semibold uppercase tracking-widest text-slate-400 mb-2">Executive Summary</p>
              <h2 className="text-xl font-bold text-slate-900 mb-1">
                {data.isCustomData ? data.companyName : "FETech Analytics"} — Business Performance Report
              </h2>
              <p className="text-sm text-slate-500 mb-5">{data.period} · Generated {now}</p>
              <p className="text-sm text-slate-600 leading-relaxed max-w-2xl">
                This report was automatically generated by analysing {data.isCustomData ? "your uploaded" : "demo"} sales data
                across {data.monthlyRevenue.length} months of trading. The system evaluated revenue performance,
                customer behaviour, product margin, return rates, and forward-looking forecast accuracy
                to surface {tagged.length} structured insights with recommended actions.
              </p>
            </div>

            {/* Data summary chips */}
            <div className="flex flex-wrap md:flex-col gap-2 md:min-w-[200px]">
              {[
                { icon: Database,  label: "Data source",   value: data.isCustomData ? data.fileName ?? "Uploaded CSV" : "Demo dataset" },
                { icon: Calendar,  label: "Period",        value: data.period },
                { icon: Activity,  label: "Insights",      value: `${tagged.length} findings` },
              ].map(({ icon: Icon, label, value }) => (
                <div key={label} className="flex items-center gap-3 rounded-lg border border-slate-100 bg-slate-50 px-4 py-2.5">
                  <Icon className="h-4 w-4 text-slate-400 shrink-0" />
                  <div>
                    <p className="text-[10px] text-slate-400 uppercase tracking-wide font-semibold">{label}</p>
                    <p className="text-xs font-semibold text-slate-700">{value}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* KPI strip */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-6 pt-6 border-t border-slate-100">
            {[
              { label: "Total Revenue",     value: `$${(totalRevenue / 1_000_000).toFixed(2)}M` },
              { label: "Total Orders",      value: totalOrders.toLocaleString() },
              { label: "Active Customers",  value: totalCustomers.toLocaleString() },
              { label: "Health Score",      value: `${healthScore.overall} / 100` },
            ].map(({ label, value }) => (
              <div key={label} className="rounded-xl bg-slate-50 border border-slate-100 px-4 py-3 text-center">
                <p className="text-lg font-black text-slate-900">{value}</p>
                <p className="text-[11px] text-slate-500 font-medium mt-0.5">{label}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Health Score */}
        <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
          <HealthScoreCard healthScore={healthScore} />
          <div className="xl:col-span-2 rounded-xl border border-slate-200 bg-white p-5 flex flex-col justify-between">
            <p className="text-[11px] font-semibold uppercase tracking-widest text-slate-400 mb-3">Findings Summary</p>
            <div className="grid grid-cols-2 gap-3 flex-1">
              {TYPE_ORDER.map((type) => {
                const Icon = SECTION_ICON[type];
                const count = grouped[type].length;
                return (
                  <div
                    key={type}
                    className={cn(
                      "rounded-xl border p-4 flex items-start gap-3",
                      type === "critical"    && "border-red-200 bg-red-50/50",
                      type === "warning"     && "border-amber-200 bg-amber-50/50",
                      type === "opportunity" && "border-blue-200 bg-blue-50/50",
                      type === "positive"    && "border-emerald-200 bg-emerald-50/50",
                    )}
                  >
                    <Icon className={cn("h-5 w-5 shrink-0 mt-0.5", SECTION_COLOR[type])} />
                    <div>
                      <p className="text-2xl font-black text-slate-900">{count}</p>
                      <p className={cn("text-xs font-semibold", SECTION_COLOR[type])}>{SECTION_LABELS[type]}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Insight sections */}
        {TYPE_ORDER.map((type) => {
          const items = grouped[type];
          if (items.length === 0) return null;
          const Icon = SECTION_ICON[type];
          return (
            <section key={type}>
              <div className="flex items-start gap-3 mb-4">
                <Icon className={cn("h-5 w-5 shrink-0 mt-0.5", SECTION_COLOR[type])} />
                <div>
                  <h3 className="text-sm font-bold text-slate-900">{SECTION_LABELS[type]}</h3>
                  <p className="text-xs text-slate-500 mt-0.5">{SECTION_DESCRIPTIONS[type]}</p>
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">
                {items.map((insight) => (
                  <div key={insight.id} className="relative">
                    <InsightCard insight={insight} />
                    <span className="absolute top-3 right-3 text-[10px] font-semibold text-slate-400 bg-white/80 rounded-full px-2 py-0.5 border border-slate-200">
                      {SOURCE_LABELS[insight.source]}
                    </span>
                  </div>
                ))}
              </div>
            </section>
          );
        })}

        {/* Action checklist */}
        <div className="rounded-xl border border-slate-200 bg-white p-6">
          <p className="text-[11px] font-semibold uppercase tracking-widest text-slate-400 mb-4">Priority Action Checklist</p>
          <div className="space-y-2">
            {tagged
              .sort((a, b) => TYPE_ORDER.indexOf(a.type) - TYPE_ORDER.indexOf(b.type))
              .map((insight, idx) => (
                <div key={insight.id} className="flex items-start gap-3 py-2.5 border-b border-slate-50 last:border-0">
                  <span className="text-[11px] font-bold text-slate-400 w-5 shrink-0 mt-0.5">{idx + 1}</span>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap mb-0.5">
                      <span className={cn(
                        "text-[10px] font-bold uppercase tracking-wide",
                        SECTION_COLOR[insight.type]
                      )}>
                        [{SECTION_LABELS[insight.type]}]
                      </span>
                      <span className="text-[10px] text-slate-400">{SOURCE_LABELS[insight.source]}</span>
                    </div>
                    <p className="text-xs font-semibold text-slate-800 leading-snug">{insight.title}</p>
                    <div className="flex items-start gap-1.5 mt-1">
                      <ArrowRight className="h-3 w-3 shrink-0 mt-0.5 text-slate-400" />
                      <p className="text-xs text-slate-500 leading-snug">{insight.action}</p>
                    </div>
                  </div>
                </div>
              ))}
          </div>
        </div>

      </div>
    </>
  );
}
